//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jetproger.Tools.Resource.Bases {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jetproger.Tools.Resource.Bases.ResourceNames", typeof(ResourceNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        internal static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The config does not specify the url of the application service (node &lt;AppHost&gt;).
        /// </summary>
        internal static string AppConfigAppHostName {
            get {
                return ResourceManager.GetString("AppConfigAppHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory busy by application.
        /// </summary>
        internal static string AppMemory {
            get {
                return ResourceManager.GetString("AppMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The config does not specify a listening port (node &lt;AppPort&gt;).
        /// </summary>
        internal static string AppPortNotSpecifiedName {
            get {
                return ResourceManager.GetString("AppPortNotSpecifiedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you want quit ?.
        /// </summary>
        internal static string AskExit {
            get {
                return ResourceManager.GetString("AskExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation||Confirmation|Confirmation|.
        /// </summary>
        internal static string AskTitle {
            get {
                return ResourceManager.GetString("AskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binaries data.
        /// </summary>
        internal static string Binary {
            get {
                return ResourceManager.GetString("Binary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons.
        /// </summary>
        internal static string Bitmaps {
            get {
                return ResourceManager.GetString("Bitmaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes/No.
        /// </summary>
        internal static string Boolean {
            get {
                return ResourceManager.GetString("Boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Data Management Studio.
        /// </summary>
        internal static string Caption {
            get {
                return ResourceManager.GetString("Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cascade.
        /// </summary>
        internal static string Cascade {
            get {
                return ResourceManager.GetString("Cascade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key bearer not found for certificate {0}=[{1}].
        /// </summary>
        internal static string CertificateKeyName {
            get {
                return ResourceManager.GetString("CertificateKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate {0}=[{1}] not found in current user store.
        /// </summary>
        internal static string CertificateStoreName {
            get {
                return ResourceManager.GetString("CertificateStoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session [{0}]: no command defined to execute(CommandRequest.Command).
        /// </summary>
        internal static string CommandNotDefinedName {
            get {
                return ResourceManager.GetString("CommandNotDefinedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer name.
        /// </summary>
        internal static string ComputerName {
            get {
                return ResourceManager.GetString("ComputerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File of configuration.
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant.
        /// </summary>
        internal static string Constant {
            get {
                return ResourceManager.GetString("Constant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local scope.
        /// </summary>
        internal static string Context {
            get {
                return ResourceManager.GetString("Context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/Time.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guest.
        /// </summary>
        internal static string DefaultUser {
            get {
                return ResourceManager.GetString("DefaultUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        internal static string Del {
            get {
                return ResourceManager.GetString("Del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog.
        /// </summary>
        internal static string Dialog {
            get {
                return ResourceManager.GetString("Dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Net version.
        /// </summary>
        internal static string DotNetVersion {
            get {
                return ResourceManager.GetString("DotNetVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drives.
        /// </summary>
        internal static string Drives {
            get {
                return ResourceManager.GetString("Drives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editors.
        /// </summary>
        internal static string Editors {
            get {
                return ResourceManager.GetString("Editors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewers.
        /// </summary>
        internal static string Faces {
            get {
                return ResourceManager.GetString("Faces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        internal static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder.
        /// </summary>
        internal static string FolderOpen {
            get {
                return ResourceManager.GetString("FolderOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full access.
        /// </summary>
        internal static string Full {
            get {
                return ResourceManager.GetString("Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grids.
        /// </summary>
        internal static string Grids {
            get {
                return ResourceManager.GetString("Grids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique identifier.
        /// </summary>
        internal static string Guid {
            get {
                return ResourceManager.GetString("Guid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        internal static string Horizontal {
            get {
                return ResourceManager.GetString("Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string InfoTitle {
            get {
                return ResourceManager.GetString("InfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string InfoTrace {
            get {
                return ResourceManager.GetString("InfoTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer.
        /// </summary>
        internal static string Integer {
            get {
                return ResourceManager.GetString("Integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to differ from the login.
        /// </summary>
        internal static string LikeLogin {
            get {
                return ResourceManager.GetString("LikeLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of objects.
        /// </summary>
        internal static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login or password is invalid.
        /// </summary>
        internal static string LoginInvalid {
            get {
                return ResourceManager.GetString("LoginInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login can not be longer than 16 characters.
        /// </summary>
        internal static string LoginLength {
            get {
                return ResourceManager.GetString("LoginLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        internal static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading modules....
        /// </summary>
        internal static string MessageLoading {
            get {
                return ResourceManager.GetString("MessageLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non connected to server.
        /// </summary>
        internal static string MessageNonConnect {
            get {
                return ResourceManager.GetString("MessageNonConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is not changed.
        /// </summary>
        internal static string MessageNonPassword {
            get {
                return ResourceManager.GetString("MessageNonPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start application {0}.
        /// </summary>
        internal static string MessageStart {
            get {
                return ResourceManager.GetString("MessageStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully connected to server.
        /// </summary>
        internal static string MessageSuccessConnect {
            get {
                return ResourceManager.GetString("MessageSuccessConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password successfully changed.
        /// </summary>
        internal static string MessageSuccessPassword {
            get {
                return ResourceManager.GetString("MessageSuccessPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create type: {0}, {1}.
        /// </summary>
        internal static string MetaCreateType {
            get {
                return ResourceManager.GetString("MetaCreateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type: {0}, {1} does not implement interface {2}.
        /// </summary>
        internal static string MetaImplementInterface {
            get {
                return ResourceManager.GetString("MetaImplementInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        internal static string MssqlCommandName {
            get {
                return ResourceManager.GetString("MssqlCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contain digits.
        /// </summary>
        internal static string NoDigit {
            get {
                return ResourceManager.GetString("NoDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contain lowercase letters.
        /// </summary>
        internal static string NoLower {
            get {
                return ResourceManager.GetString("NoLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No access.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contain special symbols.
        /// </summary>
        internal static string NoSymbol {
            get {
                return ResourceManager.GetString("NoSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contain uppercase letters.
        /// </summary>
        internal static string NoUpper {
            get {
                return ResourceManager.GetString("NoUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not filled field [Code].
        /// </summary>
        internal static string NullCode {
            get {
                return ResourceManager.GetString("NullCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not filled field [Login].
        /// </summary>
        internal static string NullLogin {
            get {
                return ResourceManager.GetString("NullLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not filled field [Name].
        /// </summary>
        internal static string NullName {
            get {
                return ResourceManager.GetString("NullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric.
        /// </summary>
        internal static string Numeric {
            get {
                return ResourceManager.GetString("Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating system.
        /// </summary>
        internal static string OperatingSystem {
            get {
                return ResourceManager.GetString("OperatingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password change.
        /// </summary>
        internal static string PasswordChange {
            get {
                return ResourceManager.GetString("PasswordChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password is not confirmed.
        /// </summary>
        internal static string PasswordConfirmationInvalid {
            get {
                return ResourceManager.GetString("PasswordConfirmationInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string PasswordNew {
            get {
                return ResourceManager.GetString("PasswordNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old and new password must not be the same.
        /// </summary>
        internal static string PasswordNewInvalid {
            get {
                return ResourceManager.GetString("PasswordNewInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        internal static string PasswordOld {
            get {
                return ResourceManager.GetString("PasswordOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        internal static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous value of cycle.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proccessed.
        /// </summary>
        internal static string Proc {
            get {
                return ResourceManager.GetString("Proc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor count.
        /// </summary>
        internal static string ProcessorCount {
            get {
                return ResourceManager.GetString("ProcessorCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        internal static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of values.
        /// </summary>
        internal static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read only.
        /// </summary>
        internal static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object.
        /// </summary>
        internal static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        internal static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contain at least 8 characters.
        /// </summary>
        internal static string SmallLength {
            get {
                return ResourceManager.GetString("SmallLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        internal static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel sort.
        /// </summary>
        internal static string SortCancel {
            get {
                return ResourceManager.GetString("SortCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is not secure enough, he must:.
        /// </summary>
        internal static string Strength {
            get {
                return ResourceManager.GetString("Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        internal static string Tables {
            get {
                return ResourceManager.GetString("Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total memory.
        /// </summary>
        internal static string TotalMemory {
            get {
                return ResourceManager.GetString("TotalMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trees.
        /// </summary>
        internal static string Trees {
            get {
                return ResourceManager.GetString("Trees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type not found &quot;{0}&quot;.
        /// </summary>
        internal static string TypeNotFoundName {
            get {
                return ResourceManager.GetString("TypeNotFoundName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &quot;{0}&quot; is not a subtype of &quot;{1}&quot;.
        /// </summary>
        internal static string TypeNotSubtypeName {
            get {
                return ResourceManager.GetString("TypeNotSubtypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types.
        /// </summary>
        internal static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        internal static string Vertical {
            get {
                return ResourceManager.GetString("Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewHelp.
        /// </summary>
        internal static string ViewHelp {
            get {
                return ResourceManager.GetString("ViewHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        internal static string Window {
            get {
                return ResourceManager.GetString("Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows user name.
        /// </summary>
        internal static string WindowsUser {
            get {
                return ResourceManager.GetString("WindowsUser", resourceCulture);
            }
        }
    }
}
