//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jetproger.Tools.Resource.Bases {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcePictures {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcePictures() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jetproger.Tools.Resource.Bases.ResourcePictures", typeof(ResourcePictures).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8
        ///        YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAIhSURBVDhPrZNdSFNhHMb/4kUEQkE3kt2NIOgqkKAvCIxY
        ///        oBYU0U0RhVaEhA3KymSaTRa6tiwaLrfmIZZszs2tjW1HZM7ISLZctZKdyj6gIIuoOFb7eDp7FY9zojc9
        ///        8Lt44X1+z8370n+L4gCPhZRV81i1O4ii7QHQJj9ogw+0zgtaMwBaKUH9ErPJFZSX3jAqGgRsUyVRXjeB
        ///        jbUvoTiSQOnB5yjZ9wzFyhhoZxS0RYJ0+YL5lFYGsaIiCNo8u1wmLZe4QUUSbDmHRhbYfGPIZrNL8ieV
        ///        wc/pDKZ+pPFhKoVy5TFZwA2Msks9rhGYHWEYbYPs3NnjR4fJjau3+lj5vJZDfa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8
        ///        YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAI9SURBVDhPddHbS5NxHMfxGUHRAfTKi/6HroKCugyCoG7C
        ///        i246XERFRgfrIjIKC6HEyi4yjVbayg6aqZVK2kGziG2WeXYHndNtOuech+fRqXv3fTbdJo/+4LOLh31f
        ///        fH7fn2H5FLdOK+XdKlW9Ku97VCq7FSq6FMo7Z7jbEiKvKWhb+uvq53WHwpaSjdFsK0zDM0k8odkIT8wh
        ///        bjYE1kbedsxw0bGPB+HjUaDIQjzqfCSawp9Bsmv9qyNlbVMcsewmy3NgTUANRyhoCnCp2ptAtMpHrXs4
        ///        1LyDDPNOMtp2RYHlpF9PTwCSCTVCTt0IS+MxQBtaLWmmzWzIXU9xUhttJ/e++B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8
        ///        YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAKmSURBVDhPrZPrS1NxHMbP36L/QVAhUSFBr4pe7EXQG1Ez
        ///        tWleMIRsI5EMZ3ghZ2o6FHNbuUTUOd3J3dyatqm7uPvMue1Mdxzb3NmOlsHTHKshSBD0wOfd9/PA93ch
        ///        /nv03uNirfeEp3GzvhVXhiEdaWbZxvgUliRv0ZQszo9dHJUrw/nsyET80e/YOWDhpZgc/v0MnOEMpo2H
        ///        Eak+ysmPnw9pT3EUtlR6lz6G5VscEm0IXTNudMpcGCV3YHQewhNhIFIF06Nk4HzJgi1ZNL+ZoHaiLL64
        ///        Y2jPSiOkH6EYi2Asg5m1MNokNig3I3AEj9A376N6ZJ6ivE4QsjWavx1KY8OfAF [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AskExit {
            get {
                return ResourceManager.GetString("AskExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8
        ///        YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAIzSURBVDhPrZLtT1JRHMfvP9W71sPWq9Zqs+bsRbRGzEWt
        ///        1nLpMBPReU0CkauAECIZqKDiRNEkrGCUTO8NcqvZrNUsHkK8lwe5vurbgbGKwexFne3z4uyc7+f8zu8c
        ///        6r+MMS+nsc1xySE3K2iddXBUo3exgmWWHajEKWp0nkt9T6d/5AsFFPbFQ9nNi0jxORinWb4Sp6jSybl8
        ///        AcMLO9AsRKFcnIJ9g4Er1gNnVIWhoBrXRs24Yw2h1foO6ZwIxv1GqMQpaoCUWbIbF3dALy3Dvs5g8m0L
        ///        LOvNMK5JYYrIofZ3Qz7igML2HimhjiBHBCNLX6H0jWOCnGqKyDD46hLUwYugXz [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bitmaps {
            get {
                return ResourceManager.GetString("Bitmaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8
        ///        YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAJmSURBVDhPrZP9SxNxHMfvb/Fh/VBI9VNY4LSQapG65UPp
        ///        dU7dg+RTWCLqbeoWuSLRhZhEqJlDISiwgphWSEEESmEEdgnWuq3pZpv3dZ4Lend33G0IEgS94fPb5/V5
        ///        fx6+X+q/67erMTPptrM7vVaOdJsF0sEIQifDxToYNnblYqaatrdEt92047QHN1xNID4vxCdjSgi+QYRZ
        ///        O9Zby4Lhy2UmNX23ZJg4rSQ+7MavuWmIEzeQ8FxSQrzvQXJ2ChGvE6v2EhKwF+0usu2sz0h0WvjYsEuB
        ///        t3prldAkOMwQuqqx89yHtVud+FJ3il82GzJUnKIIW+uI9DSk4Z4akO4aFQfiHQ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8
        ///        YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAIhSURBVDhPrZNdSFNhHMb/4kUEQkE3kt2NIOgqkKAvCIxY
        ///        oBYU0U0RhVaEhA3KymSaTRa6tiwaLrfmIZZszs2tjW1HZM7ISLZctZKdyj6gIIuoOFb7eDp7FY9zojc9
        ///        8Lt44X1+z8370n+L4gCPhZRV81i1O4ii7QHQJj9ogw+0zgtaMwBaKUH9ErPJFZSX3jAqGgRsUyVRXjeB
        ///        jbUvoTiSQOnB5yjZ9wzFyhhoZxS0RYJ0+YL5lFYGsaIiCNo8u1wmLZe4QUUSbDmHRhbYfGPIZrNL8ieV
        ///        wc/pDKZ+pPFhKoVy5TFZwA2Msks9rhGYHWEYbYPs3NnjR4fJjau3+lj5vJZDfa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Caption {
            get {
                return ResourceManager.GetString("Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8
        ///        YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAHfSURBVDhPlZJNaxNhFIXzcxLiQoqgASvaKNWFpW7ciOCm
        ///        C7txI4L4URvJoorgoqCo1RZUWmwl2GWqYGlFFwYUOxMb0zYmVkwkk6+ZSZqYx/tOGquQtPHAhZlhnnPO
        ///        e2dcOwlmSIYOO6OuNx93piZcK684818mf2AzQiXzkGrhlcD1TZMn25v8DZe/36Lyc8K5b8CwOuGDpYvt
        ///        TRxYKivYTl2l/GNUZq5hMt1DvZYlfrervYl6UVVWsDPfhh2Tan6O4vJNzPgxfpVfs3x7d3uDmr0kDUa2
        ///        TByjAAWtl1xknxzvOdplT2sDtYP0wjkBrpH/0I0ZO421epai3o/xfg9VI4g25C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8
        ///        YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAHGSURBVDhPjZH9S1NRGMfPP5sIJSv6ofohQsQKiYgQoqJZ
        ///        1uyFRaHGyrKyNzHydaWk121u3r02TVs6N+3T89yzi7ewrQNf7j08z/k893yuufKuzL9i/mdpY3qDA9M7
        ///        9q01xAdc/bSfIOTSy1JzSO/bMqub0DcN1yctQPd+LjzPNwdcfl0i9wOi83A3Dv2zcGMKekYKnB/Jc+5p
        ///        jrOxHN1PsnRJOodczgy6+9CLo0WKP+GZA8OL8GgBHnzBOxS8SjBD8xVOPUxbSI9MWduG8Qy8WYHRBMSW
        ///        oHPY9ZqDbv72c/x+CtMdy7K5A5+LMJ2Djy68T8PpxxnPQbjh5g8/clifoYEERi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8
        ///        YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAKISURBVDhPdZLLTxNRFIfvwj/AmJjon+DGdOnCxI0rF+5Z
        ///        0Y1RIwZduDBoIGiMSlAQMUjkjTa8RBAVFQsSCc8ByqPl0TI8bHkUmPJoy6PweWaAsJh4kjOTTO733fO7
        ///        c9VRFfZvxmp9cRrG43wai1Pvi1HnjVE7GuVFxxpZ7cakua67W3d4zp1p9Zw9wRelSizYrKqRGGaF1u29
        ///        trVPUe8a2e6l6c7mPsOtFJuXTlMm70NcqZqRqLX4bZ+9zYpFV3HXpaJpQRovXOSlwJlKtR7iSrk8G/8V
        ///        7G0ZhGocGCOKsrKnVFb2kXH33UB6ev3JQ1ypCm2dhQ0oHYSifijUDuCiLoPpcg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8
        ///        YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAKHSURBVDhPdZLLTxNRFIfvwj/AmJjon6CrLl2YuHHlwj0r
        ///        ujFqxKALFwYNiMaoBAURg0RAHtrwEkEUVAQkEp4DlEfLo2V4tZTnlEdb3p9nhhIWE09yZpLJ/b57fneu
        ///        Oqr8vnC0yhujdizGl9EYNd4o1Z4oVSMRXrav8aJtZcJc19WlO9znzrS4z57gm1JFFmxW+XAUs4Lr9l7b
        ///        OqCgZ43M5sWpjoYOo1kpNi+dpljecVypyuGItfhdr73NikZWaa5ORtMC1F24yCuBHynVEseVcrk3/ivY
        ///        3zIIVjowhhXFxc8oK+sl7e77/tTUmpNxXKlSbZ3QBnwYgII+yNcO4YJOg6kSBx [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Editors {
            get {
                return ResourceManager.GetString("Editors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8
        ///        YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAFfSURBVDhPrVHbSgJRFPW3+oi+o48IqQi6vPUQVE8hBWZ3
        ///        SKOCLA0lb6UhNeWQaEEJYmn44BzHleuMRxqdKR/asFh7n9l77XXOeFSE0gaCKQtHSQP7cQP+K4H1sMDq
        ///        iYHpQBtLQYGFQ4HZ3TamAgZ6o1ZQIKEDsScg8gCE88BpFghmgIMkEIhb2IwCvggw4/8cFlDbd7rbNy4F
        ///        1s4MuXV+T0gHhHdLwNvlSV/VLpDIv9oPfola08TiyrbVPzY+gVHBQeIiU7ILkOnA7JiOaLVNKdBsddwF
        ///        yGzWilXcP1cls+Y5a3Lo+EUK5LSyswMlosCaA+/1jsxLNRPFtwbiORcBDnGbAq [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Faces {
            get {
                return ResourceManager.GetString("Faces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8
        ///        YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAGfSURBVDhP1ZFbKMNRHMf3vqTksoS5RMmKcilK4UkoQh5Q
        ///        aiW5RKTVIg+uNdqktlxyn/Rv2gNLHtY8SEpEJMmyDLm0aSEbW33tnLNlc4kHL371fTrn8/meX4f3J7Ok
        ///        VuBjPEc/D7lsuVyG436V5tnC4fF85PcS31ZvuJkhLE7KaObH+2lmlD1+8eBM8GIz+MXxoIPTqoHTsgDX
        ///        lRIukwwuYwdej9rwtF2Hp81KSFvETEJaKORZwW7zAc2DDDxshn1HjMeNctj0RdgbE7wLyPN8BZ9gdyuB
        ///        SSuBr7k0bCn4aBBXMMG0ex8i8DY7bya+ha0r2bhQJ2FdxkdVaf67gDaTnT2w86 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8
        ///        YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAD3SURBVDhPvZGxDYMwEEU9BTtQu2IISmo6r8AG1KmQPEKK
        ///        7EDP9YxzuX822AhMUkSx9GVj3fv/OJu/rWmaGPKeOF59v5zzBwhGRMR6v64rv56Pk+Z5LiYty6KwGqCY
        ///        yDMzReHsb002eDcIUIJV5A4dpRm4o2kyyOFgcKWPBvgdKE/PtXUyjmMww6UmRnj/Lip0QgLDKBmIcNaB
        ///        Zi2fZaXUygBll6fUNwV8TL8GN3mB91lsBvfpEZZk8oadtWmQGEY5PQcDjPS+75MBWgnpGIwpStsWIR31
        ///        EQ8G0DAMUuBkOJDltm25aRq2AtR1zV3XcVVVukf0F8uYN/Oj9VU9uRLEAAAAAE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FolderOpen {
            get {
                return ResourceManager.GetString("FolderOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8
        ///        YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAFZSURBVDhP1Y/LSwJRHIX9l4LoQWCrwk2r2gtujGhhLxc9
        ///        FhEtQiOoIC2jGqhslLQiNVKyt02GiCGRbvLqaLZwNZkPPHmHKJjGbFkHzuIuzvf9ruLvZNb+AgObFTtj
        ///        zWKSeYbekkHfYhpqI4/u6RRU40m06wmUIwQfs69QAHMOrJ5UYDouY95VgsFZxJStgLGtNwyvC+hfFqBd
        ///        EqDUReQBRmrfyWKiateZM9DM8eipmjtHCdqGCJoHEmgZJGjqvfsO2HYFUa6UZZsvlpATSuBzRcQzBbR2
        ///        aWsD/Fzss/R9dPGAQ38UDm9EBBx4uZ8B0krtrPum/gW+wKNopmNqZj1hbB6EEH [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Grids {
            get {
                return ResourceManager.GetString("Grids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8
        ///        YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAKqSURBVDhPrZPtT5JRGMafv0X/Az3Pl/pQfijXLEEp/WBZ
        ///        YZmYtXQVZXtcha/4iihgQzSJMjEzsSQlKF4kRRQU8+XJiRm0tdUXyFqWVweiOTfX1ta1/b7d132f69zn
        ///        MP9dQs1y8hFVgMtQ+PkD9VORNPlkZL98gt8nd3N75M7kRNnuEqgWRIcU/nBxtw/dtiAGXOtxuiyrEKtf
        ///        g+UsYcKNiRLlO3VYNSdKb5yONgwtwewNo3M0iCrjAm4/fAOFaQlG+xqqBwJgiwej5OLQziYZqtmk9Kbp
        ///        UMxsmgyDo6brBj96ne/Q61jD1R4fpPf86Hmxgqp+H9hCY4ic7k9K2BnmoGK6ok [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InfoTrace {
            get {
                return ResourceManager.GetString("InfoTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8
        ///        YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAALvSURBVDhPbZJbSJNhGMcNijIiiAiii7yoi04XFlRe1EUF
        ///        QnSmA2lBddGNRAdqojCzNCQPM2XOuVJTWzEVR2mZTXM01zJbaZlaeVjTrEa6aXbYp7Nf79aHH0V/+PPC
        ///        w/v8/s97CPtXFRUVc8rKyi6WlJRYioqKnAaDwZmfn2/Jy8u7KDxH3vZ/GY3GyNLS0r6GhgZaWlpwOp2h
        ///        1WazUVVVRVZWVl9GRkakvP1vBZNFarfdbqexsREBQiSj1WrR6/WYzeaQU1NTuzUaTbjcpkg0qCwWC1ar
        ///        lYKCgl4xboQYf0bQmZmZEWlpaYMmk4ni4mLUarVKblNUWFhoDqYHk3U63XK5PK [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8
        ///        YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAKqSURBVDhPrZPdS1NxHMbPf9Hc2jml4UXmRTGKSiG9qQsR
        ///        18CXNM1c5kvbzl7UlLYJQ2dapIHTuSRFNMtSq805k6lzNp1TysRlU0LM3fRCtWH0Yk/njEkaFQQ98PD7
        ///        Xnw/z++d+O/Knk6IOj1xVJ3uOOxLse0PJFtjA0JbjE9o3atOGdgTFW77vXJc8aJUx0G/ypGBDq8BvUud
        ///        IbcvNKLIloLEbsp/rJsUhdu3K8d5RCQcFQTrZ7WwrvSh9fl16GbLQmZry0ov6iYv4oCRHzx0g7c95NR4
        ///        XKTILlhjYbaxwiNBqbsIiskCqBiXMC6fKob55V1cdpZin4GzFmsgI8M4QWTYBR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8
        ///        YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAHfSURBVDhPlZJNaxNhFIXzcxLiQoqgASvaKNWFpW7ciOCm
        ///        C7txI4L4URvJoorgoqCo1RZUWmwl2GWqYGlFFwYUOxMb0zYmVkwkk6+ZSZqYx/tOGquQtPHAhZlhnnPO
        ///        e2dcOwlmSIYOO6OuNx93piZcK684818mf2AzQiXzkGrhlcD1TZMn25v8DZe/36Lyc8K5b8CwOuGDpYvt
        ///        TRxYKivYTl2l/GNUZq5hMt1DvZYlfrervYl6UVVWsDPfhh2Tan6O4vJNzPgxfpVfs3x7d3uDmr0kDUa2
        ///        TByjAAWtl1xknxzvOdplT2sDtYP0wjkBrpH/0I0ZO421epai3o/xfg9VI4g25C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8
        ///        YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAHfSURBVDhPlZJNaxNhFIXzcxLiQoqgASvaKNWFpW7ciOCm
        ///        C7txI4L4URvJoorgoqCo1RZUWmwl2GWqYGlFFwYUOxMb0zYmVkwkk6+ZSZqYx/tOGquQtPHAhZlhnnPO
        ///        e2dcOwlmSIYOO6OuNx93piZcK684818mf2AzQiXzkGrhlcD1TZMn25v8DZe/36Lyc8K5b8CwOuGDpYvt
        ///        TRxYKivYTl2l/GNUZq5hMt1DvZYlfrervYl6UVVWsDPfhh2Tan6O4vJNzPgxfpVfs3x7d3uDmr0kDUa2
        ///        TByjAAWtl1xknxzvOdplT2sDtYP0wjkBrpH/0I0ZO421epai3o/xfg9VI4g25C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8
        ///        YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAALHSURBVDhPfZJtTFJhFMf92tdel7WsFFupy3fN5lRUTGuD
        ///        Wb7NF6xUTFHMaVjGCkTyJUDECDUHjLQZfFBXbQjL1K1ZizQrWvbB+mA5c8syrUT5x70qhK3+291z7nPP
        ///        +d3/c57jtlEv3ozijkEFrqoQ7BtMCDRcXFfKoL7di9yWILR26NCm0qGpvRt9xhGsla3q8eggUstiQC+O
        ///        APXsAUTnUhCVvR/xhZ5IKvMGg+eDZYAsevlqAk2qPlcAs5yOJ+PDjs3mngY0qATonZGDY0hFNHMfLJOL
        ///        MFu+oV0/hlqp2hWwUfp7RlQrSiAZPY98DR3+kdvw7O08hsbmoOh8josCuRMQlb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8
        ///        YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAIMSURBVDhPYyAEalaX/Y84YPnfdpH2/86Vnf+hwsSD3EUZ
        ///        /2f8SwXjqEM2/z36Xf7vPrgbu0EgCZCNQSsc/wftNQdjkKapf1P+d32N+V/3NuR/4kXH/7pdav+nb5yG
        ///        akjHhub/fhtM/7d+jIBraP4QDtaU+8jzf9pdl/+Jtxz/R1+z/R9wzvS/YD03woD29U3/nVfpwjWUv/AH
        ///        awDhsEuW//2BGtxP6P+3P6z133CX4n+VhRL/Neo0EAaAAghmi8Nmrf/605T/e0x0+Z88Pfm/UYMRWJPu
        ///        drn/SmvE/vN3cIHFoVohwGiZwn/HPdpgvzWsqEORBCkWW8r/n38613+NJvX/i7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8
        ///        YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAJJSURBVDhPfZNbSNNhGMbXhUQFiVI4o8SB5EXRiYWQHZBI
        ///        0AtvgqDsIqIbr6IgCS+86yIqLUJoaJEHjCzTtTzMQ23TuWyb0zla003dytiwubE8JCS//D5cJHO98PD/
        ///        Lr73x/M+3/tX/FtNJcexqHdjP6Wk9Wg6RleU/rEIfcMzjI5+Y/3a5uXx/KB3cglDbibBm0cIV6qpv6BG
        ///        oYHsJijSwZPBGF1GXyLIMxHkpW+VawY42QHte9MI3T7M9NVsnqv3SEhcZb2/edvl2giZ8kcoNUFpxyLl
        ///        rQHuNntxnM1k9nou48UZDJ3O5Ypmmv2amHTT8uHrRoBw4PT/Qt/jRa+foK3NjS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8
        ///        YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAJVSURBVDhPfZNdSNNhFMZ3UXd5kVQEUS0oKqgZRg0qCEVm
        ///        lkH2RWSRSBR1VV140cA7GebaCiF0WhKl1NJksxnDLZduLtdyaObm1mT+U5vOj/UxzYvxtHPWkjXXAw/8
        ///        L97z+z/nvOcV/athbxADA0H0uL/h7WAY5v45mHoD6Ha4UdxyHOfbj+DP0WR5vdPo8M1D3g8c0gOi2iWL
        ///        nwL5z4pwb7EE5dOnsKNmQzKE/vrcH8VlS6zYAKx+HC/c/mgImZoJ7FJuhHq+hAG3xgshe5eFzLurliAj
        ///        o3O4aAWKDRHcbh5HZdNnNDYOoKHBhdzKDC6uxRXciVxAqS+XAfvbtmJdxZo4hP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8
        ///        YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAH0SURBVDhPnZBdSFNhAIYH0UV0E11Fv3jpzRCxEELIi4Jk
        ///        ghDGVh5iiGYpoWENEWLI2jAxC2QML/wZiO4mkC2zKRLBshhW7uJsxCEUiZLDzKKkizhP3znHc5Y5Invh
        ///        5YMDz/O933EUCVYXkwv6+e8pO1piw1aX07ldSTgsesl5hKB0mpP7HHgqa7YJ/7qqfP8e7klVpAYbkSc7
        ///        GGmtZlerngbaSYfryc71kH3SjZzoNIDfV1XvtVftTM2hA0zePkd2KkQ2cRc52kyxVRPd7p2CTxP6vIOk
        ///        hqO8jjQzP+BlyFNCsVUvB68WBNrGLDqsfcugfX3B0rMMb0dbuVXrBOIUW/VqqK [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8
        ///        YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAE4SURBVDhPY0AHN84s/X9mb8//Xcsr/m+YnfN/3ayc/5vm
        ///        F/zfu7rp/5n9s/9DlWEHII23z8/9/+L+2v+f3+z8/+vrITAGsR/fWvn/4pEp/3esqMJuyI7Fxf///jxK
        ///        FJ5aE4JpCMiAL1ez/n9/Mev/r89b4YpBLvj9Yf3/L497wPJPd9hiNwDkzw9HnMCKQIq/vV70/8v95v8f
        ///        Tgf8f7tV9v/LFYz/Hy1i+H97DhN2A0ABRqwBfcW+mAaAQpsiA1ZPTaefAW1ZrpgGLO1PHgQGvKfEgNkt
        ///        kUS7oDLWBrsBz/c6//94OQ2vAZemcWA3AARW9wf/3784+v+VA+X/n92cCjbgzT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tables {
            get {
                return ResourceManager.GetString("Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8
        ///        YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAACsSURBVDhPYxi8oHvVq//lc178V/Ga8R8qRBoom/Py/5VH
        ///        P/4bJJ0gzwC36uf/9ZNPkO8CEAAZAmWSB1yqnpFmACjgQDi+99l//+Zn/x0qnv03K3jwXydiy3/1wGX/
        ///        lT2n4jcQpBnKBAOQAVAmGJBsgF0ZqgEqHlNoaABIM3LCwcavmPviv6r3TOyGoCccdH75XAjfEJg2QHwM
        ///        gJ5w0PnuQL5BygncLhggwMAAAFbrlEMcdlO7AAAAAElFTkSuQmCC.
        /// </summary>
        internal static string Trees {
            get {
                return ResourceManager.GetString("Trees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8
        ///        YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAIVSURBVDhPlZPBThpRFIb7LoJP0KBbow3OUNAX6KIb25S4
        ///        cqchKagbw0IwaVK7aBukJcNAg5YOxDQBMTXGjDHGhbFNjG1qsbaVqgUGh/l772EoM6QuPMk/k3uG853/
        ///        3BxuWeNFbgdxRUUst4clZfefYtkdxDIqFuUNPF0qYm37AGaJPXgxDNg+GoZhO889W4GzfwRr6mErv7V/
        ///        gZsoniognVfR2+dDUf0IAvj9fjRZJ0XJQxA9SEhp/P6jY+zBI3yvNJBIvcPgHQGLzyUCOFmxs38Uva6R
        ///        FiAcDkNvGlRcqzfhHhZxdqFjMhBC+WeDio9O6hgYFAgQjMoIRSU42CgEyOXfo3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8
        ///        YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAGtSURBVDhPxZJBSJNhGMcHHQMP3UqXeJIRfIzRQQgDDwnF
        ///        gkEo37QRQzZtDtFYDRFixNxQERVkjB1sDEZ2lI1aY0gUw2KYusP3hXxEIiIyhrfhIfj5fotJM8R5EP/w
        ///        54GH5/97nhdew2WKmteza3ptXOaWtpNwzb8LPy8E4ZZwn9RMyHEP2WjE3vGocYDl+jWmHZ3kFwdQlsd4
        ///        O9zFuwm5ccCn4CiFSA9q7g3qxwmUtI9vi4ONA+7fbGL5VTfqShg1PYmScPM9NnY+IPMLxuOKGLzB66c9
        ///        /Ii6WZ1zEnhym/nnVlLFytkQf3Kbh+EKwQ/gnfrD1ucim/FhXj6WcI4cMB6BVt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
